### ISSUE TITLE
1.12 - Meanimos game created a corrupted chunk on server

### ISSUE THREAD

**Issue by Hydraheads** [Epidra/CasinoCraft#1]
This is sort of weird, but on my server there are a tiny handful of players who have bizarre interactions with arcades. These players have things spawn off screen for no discernable reason, especially in snake.  I am not sure if this is linked to the following issue, but it seems like it could be related somehow.

The minimos machine caused a server crash loop every time somebody entered the chunk.  It was fixed by carefully extracting the tileentity from the chunk with nbt edit. Here is the report:

[crash-2020-11-11_18.25.06-server.txt](https://github.com/Epidra/CasinoCraft/files/5526645/crash-2020-11-11_18.25.06-server.txt)

Apparently, this happened while one of those players was playing the game.  As for what seemed to be causing it in data, the tileentity had these flags:

domino0x: -1
domino0y: -1
domino1x: -1
domino1y: -1

**Comment by Hydraheads** [comment]
Same crash happened but on columns
[crash-2020-11-13_23.39.40-server.txt](https://github.com/Epidra/CasinoCraft/files/5539793/crash-2020-11-13_23.39.40-server.txt)

**Comment by Epidra** [comment]
It was expected it break on columns, too, and most likely also on tretris.
That bug is a synching failure with the machine and the player and hard to track down. Not sure if it's even completely repairable on 1.12.x, but I can try to make him not crash.

**Comment by Hydraheads** [comment]
To clarify, it is a server crash, the entire server goes down everytime somebody loads in the chunk with the corrupted machine.  Perhaps the mod needs to have a failsafe if the number is out of bounds to reset the positions?

**Comment by Epidra** [comment]
Then I should look through the Save/Load system, too. Maybe some stupid oversight.
Anyway, a failsafe will come.
